const data = {
    products: [
      {
        _id: '1',
        name: 'กางเกงยีนส์ขาสั้น',
        category: 'กางเกง',
        image: '/images/p1.jpg',
        price: 170,
        countInStock: 10,
        brand: 'ไม่มีแบรนด์',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'กางเกงยีนส์ขายาว เอวโซ่',
        category: 'กางเกง',
        image: '/images/p2.jpg',
        price: 350,
        countInStock: 20,
        brand: 'ไม่มีแบรนด์',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'กางเกงเอวสูงรัดเข็มขัด',
        category: 'กางเกง',
        image: '/images/p3.jpg',
        price: 250,
        countInStock: 0,
        brand: 'ไม่มีแบรนด์',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'กางเกงขายาว ทรงกระบอก',
        category: 'กางเกง',
        image: '/images/p4.jpg',
        price: 180,
        countInStock: 15,
        brand: 'ไม่มีแบรนด์',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'กางเกงยีนส์ขาสั้น เข็มขัดโซ่',
        category: 'กางเกง',
        image: '/images/p5.jpg',
        price: 200,
        countInStock: 5,
        brand: 'ไม่มีแบรนด์',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'กางเกงยีนส์ขาสั้น เว้าโซ่',
        category: 'กางเกง',
        image: '/images/p6.jpg',
        price: 200,
        countInStock: 12,
        brand: 'ไม่มีแบรนด์',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;
  